"""rename department

Revision ID: 2d2df609877e
Revises: 9422c663a2df
Create Date: 2025-01-14 11:40:16.693546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2df609877e'
down_revision = '9422c663a2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department','departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.rename_table('departments','department')
  
    # ### end Alembic commands ###
