"""rename address

Revision ID: 616f2793e3d0
Revises: 2d2df609877e
Create Date: 2025-01-14 12:10:46.477259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616f2793e3d0'
down_revision = '2d2df609877e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','address',new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','location',new_column_name='address')
    # ### end Alembic commands ###
